closeComment: >
  While the project is free to use under the MIT licence, if you'd like to file an issue to receive support about a bug you found, a feature you'd like or if you just have a question, you'll need to be a [Bronze sponsor or higher on Patreon](https://www.patreon.com/mattlewis92) to do this.<br><br>

  Thank you! ✌️

lockOnClose: true

allowNoTemplates: true
